version: '3'

services:
  redis-local:
    image: redis-tutorial:latest
    restart: always
    ports:
      - '6379:6379'
    command: 
      - redis-server 
      - redis.conf
    volumes: 
      - redis-local:/data

  redis-dev:
    image: redis-tutorials:latest
    restart: always
    ports:
      - '6379:6379'
    command: 
      - redis-server 
      - redis.conf
    volumes: 
      - redis-dev:/data

volumes:
  redis-local:
    driver: local
  redis-dev:
    driver: local